"""add title column to sessions

Revision ID: 68b3fde92644
Revises: a1b2c3d4e5f6
Create Date: 2026-03-10 16:33:54.798525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '68b3fde92644'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_predictions_id")
    op.execute("DROP TABLE IF EXISTS predictions")
    op.execute("CREATE INDEX IF NOT EXISTS ix_annotation_images_id ON annotation_images (id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_annotations_id ON annotations (id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_email_confirmation_tokens_id ON email_confirmation_tokens (id)")
    op.execute("DROP INDEX IF EXISTS ix_images_filename")
    op.execute("""
        DO $$ BEGIN
            ALTER TABLE images ADD CONSTRAINT images_filename_key UNIQUE (filename);
        EXCEPTION WHEN duplicate_table THEN NULL;
        END $$
    """)
    op.execute("CREATE INDEX IF NOT EXISTS ix_password_reset_tokens_id ON password_reset_tokens (id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_session_images_id ON session_images (id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_session_questions_id ON session_questions (id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_user_stats_id ON user_stats (id)")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_stats_id'), table_name='user_stats')
    op.drop_index(op.f('ix_session_questions_id'), table_name='session_questions')
    op.drop_index(op.f('ix_session_images_id'), table_name='session_images')
    op.drop_index(op.f('ix_password_reset_tokens_id'), table_name='password_reset_tokens')
    op.drop_constraint(None, 'images', type_='unique')
    op.create_index('ix_images_filename', 'images', ['filename'], unique=True)
    op.drop_index(op.f('ix_email_confirmation_tokens_id'), table_name='email_confirmation_tokens')
    op.drop_index(op.f('ix_annotations_id'), table_name='annotations')
    op.drop_index(op.f('ix_annotation_images_id'), table_name='annotation_images')
    op.create_table('predictions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('model_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('predicted_label', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('model_version', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], name='predictions_image_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='predictions_pkey')
    )
    op.create_index('ix_predictions_id', 'predictions', ['id'], unique=False)
    # ### end Alembic commands ###
