"""sync schema differences

Revision ID: 9926b2b5667f
Revises: c020e43ee8e3
Create Date: 2025-11-15 17:18:42.068463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9926b2b5667f'
down_revision: Union[str, None] = 'c020e43ee8e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Check if columns exist before dropping them
    # This handles cases where different team members have different schema states
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('images')]

    # Remove incorrect columns from images table if they exist
    # These columns belong to questions table, not images table
    with op.batch_alter_table('images', schema=None) as batch_op:
        if 'question_type' in columns:
            batch_op.drop_column('question_type')
        if 'question_text' in columns:
            batch_op.drop_column('question_text')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Re-add the columns if downgrading (not recommended but included for completeness)
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_text', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('question_type', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
