"""sync_database_schema_with_models

Revision ID: c020e43ee8e3
Revises: 067bd8a806a5
Create Date: 2025-11-13 19:33:19.470344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c020e43ee8e3'
down_revision: Union[str, None] = '067bd8a806a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotations', sa.Column('session_id', sa.Integer(), nullable=True))
    op.add_column('annotations', sa.Column('question_id', sa.Integer(), nullable=True))
    op.drop_constraint('annotations_user_id_fkey', 'annotations', type_='foreignkey')
    op.create_foreign_key(None, 'annotations', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'annotations', 'sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_column('annotations', 'user_id')
    op.drop_column('annotations', 'challenge_id')
    op.drop_column('annotations', 'answer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotations', sa.Column('answer', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('annotations', sa.Column('challenge_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('annotations', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'annotations', type_='foreignkey')
    op.drop_constraint(None, 'annotations', type_='foreignkey')
    op.create_foreign_key('annotations_user_id_fkey', 'annotations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('annotations', 'question_id')
    op.drop_column('annotations', 'session_id')
    # ### end Alembic commands ###
